---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: sha256:49e29f11948fb6e7eff00ff639838d49f1b3a63110369c5a462183dca21c0812
    ports:
    - 8080:8080
    restart: on-failure:0
    volumes:
    - ./backups:/tmp/backups
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,generative-cohere,backup-filesystem'
      BACKUP_FILESYSTEM_PATH: '/tmp/backups'
      COHERE_APIKEY: 'cJuzSJQDgzm5vJXoxo77c8DTNPT9CmPdFiYq4EoY'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_EXPERIMENTAL_BM25: 'true'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-MiniLM-L6-v2
    environment:
      ENABLE_CUDA: '0'
...
